app/clientes/controllers.py
from flask import Blueprint, request, render_template, flash, g, session, redirect, url_for, Markup
from werkzeug.security import check_password_hash, generate_password_hash

from flask_login import login_user, logout_user, current_user, login_required
from urllib.parse import urlparse, urljoin
from app import db

# Confirmação de email
from app.clientes.token_confirm_email import generate_confirmation_token, confirm_token, decode_confirmation_token
from app.clientes.token_recovery_password import generate_recovery_token, recovery_token, decode_recovery_token
from app.clientes.send_email import send_email
from itsdangerous import SignatureExpired, BadSignature
import datetime

from app.clientes.forms import LoginForm, RegisterForm, RecoveryPasswordForm, ChangePasswordForm
from app.clientes.models import Cliente, ConfirmEmail, RecoveryPassword
from app.clientes.user_loader import load_user

clientes = Blueprint('clientes', __name__)

def is_safe_url(target):
    ref_url = urlparse(request.host_url)
    test_url = urlparse(urljoin(request.host_url, target))
    return test_url.scheme in ('http', 'https') and ref_url.netloc == test_url.netloc

@clientes.route('/login', methods=['GET', 'POST'])
def login(): 
    if not current_user.is_authenticated:

        form = LoginForm()
        if form.validate_on_submit():
            cliente = Cliente.query.filter_by(email=form.email.data).first()
            
            if cliente and check_password_hash(cliente.senha, form.senha.data):
                if cliente.confirmado:
                    login_user(cliente, remember=form.lembrar_me.data)
                    if 'next' in session:
                        next = session['next']
                        if is_safe_url(next) and next is not None and next != '/logout':
                            return redirect(next)
                    #flash('Bem-vindo %s' % cliente.nome)
                    return redirect(url_for('home.index'))

                flash('Seu email ainda não foi confirmado.', 'email')
                return redirect(url_for('clientes.login'))         
            flash('Email ou senha incorreto.', 'erro')

        session['next'] = request.args.get('next')
        return render_template('clientes/login.html', form=form)

    return redirect(url_for('home.index'))

@clientes.route('/register', methods=['GET', 'POST'])
def register():
    if not current_user.is_authenticated:
        form = RegisterForm()

        if form.validate_on_submit():
            cliente = Cliente.query.filter_by(email=form.email.data).first()

            if cliente:
                if cliente.confirmado:
                    url = url_for('clientes.login')
                    flash(Markup(f'Email já cadastrado. Ir para <a href="{url}">página de login.</a>'), 'erro')
                    return redirect(url_for('clientes.register')) 

                confirm = ConfirmEmail.query.filter_by(cliente_id=cliente.id).first()
                if confirm:
                    db.session.delete(confirm)
                    db.session.commit()
                db.session.delete(cliente)
                db.session.commit()
                
            nome = form.nome.data
            email = form.email.data
            senha = generate_password_hash(form.senha.data, method='sha256')

            cliente = Cliente(nome, email, senha)
            db.session.add(cliente)
            db.session.commit()

            token = generate_confirmation_token(email)
            link = url_for('clientes.confirm_email', token=token, _external=True)
            html = render_template('clientes/confirm_email.html', link=link)
            subject = 'Confirmação de email'

            confirm = ConfirmEmail(cliente.id)
            db.session.add(confirm)
            db.session.commit()

            send_email(subject, email, html)
           
            flash('Um link de confirmação foi enviado para seu email. Confirme para ter acesso a sua conta.', 'email')

            return redirect(url_for('clientes.login'))

        return render_template('clientes/register.html', form=form)

    return redirect(url_for('home.index'))

@clientes.route('/confirm_email/<token>')
def confirm_email(token):
    try:
        email = decode_confirmation_token(token)
        cliente = Cliente.query.filter_by(email=email).first()
        confirm = ConfirmEmail.query.filter_by(cliente_id=cliente.id).first()

        expiration = confirm.expiration
        active = confirm.active
        
        active = confirm_token(token, expiration, active)
        confirm.active = active
        db.session.commit()
    except SignatureExpired:
        flash('Link de confirmação de email expirado.', 'erro')
        return redirect(url_for('clientes.register'))
    except BadSignature:
        flash('Link de confirmação inválido.', 'erro')
        return redirect(url_for('clientes.login'))
    except KeyError:
        return redirect(url_for('clientes.register'))
 
    # cliente = Cliente.query.filter_by(email=email).first()
    if cliente.confirmado:
        flash('Email já confirmado. Por favor faça o login', 'sucesso')
    else:
        cliente.confirmado = True
        cliente.data_modificacao = datetime.datetime.now()
        db.session.commit()
        flash('Seu email foi confirmado.', 'sucesso')
        flash('Cadastro concluído com sucesso.', 'sucesso')
    # flash('Usuário cadastrado com sucesso.', 'sucesso')
    return redirect(url_for('clientes.login'))
    
@clientes.route('/recuperar_senha', methods=['GET', 'POST'])
def recuperar_senha():
    if not current_user.is_authenticated:

        form = RecoveryPasswordForm()
        
        if form.validate_on_submit():
            cliente = Cliente.query.filter_by(email=form.email.data).first()   
                  
            if cliente:
                # Reseta qualquer token de recuperação no db se existir
                recovery = RecoveryPassword.query.filter_by(cliente_id=cliente.id).first()
                if recovery:
                    db.session.delete(recovery)
                    db.session.commit()

                email = form.email.data
                
                token = generate_recovery_token(email)
                link = url_for('clientes.recovery_password', token=token, _external=True)
                html = render_template('clientes/recovery_password.html', link=link)
                subject = 'Recuperação de senha'

                recovery = RecoveryPassword(cliente.id)

                db.session.add(recovery)
                db.session.commit()
                
                send_email(subject, email, html)

                flash('Um link para alteração da sua senha foi enviado para seu email.', 'email')

                return redirect(url_for('clientes.recuperar_senha'))

            flash('Email não encontrado', 'erro')

        return render_template('clientes/recuperar_senha.html', form=form)

    return redirect(url_for('home.index'))

@clientes.route('/recovery_password/<token>', methods=['GET', 'POST'])
def recovery_password(token):
    try:
        email = decode_recovery_token(token)
        cliente = Cliente.query.filter_by(email=email).first()
        recovery = RecoveryPassword.query.filter_by(cliente_id=cliente.id).first()

        expiration = recovery.expiration
        active = recovery.active

        active = recovery_token(token, expiration, active)
    except SignatureExpired:
        flash('Seu link de recuperação de senha foi expirado.', 'erro')
        return redirect(url_for('clientes.recuperar_senha'))
    except BadSignature:
        flash('Link de recuperação de senha inválido.', 'erro')
        return redirect(url_for('clientes.recuperar_senha'))
    except KeyError:
        return redirect(url_for('clientes.recuperar_senha'))
    
    form = ChangePasswordForm()

    if form.validate_on_submit():
        if recovery.active:     
            # Comita senha nova e RecoveryPassword
            cliente.senha = generate_password_hash(form.senha.data, method='sha256')
            recovery.active = False
            db.session.commit()
            flash('Sua senha foi alterada!', 'sucesso')
            return redirect(url_for('clientes.login'))
        
        # Não comita nada
        # flash('Link expirou', 'erro')
        # return redirect(url_for('clientes.login'))

    return render_template('clientes/alterar_senha.html', email=email, form=form)

@clientes.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('home.index'))

@clientes.route('/perfil')
@login_required
def perfil():
    return render_template('clientes/perfil.html', nome=current_user.nome)

app/templates/components/footer.html
<div class="row">
    <div class="col-4 text-center bg-success">
        <h1>FOOTER</h1>
    </div>
    <div class="col-4 bg-primary">
        <h1 class="text-center">FOOTER</h1>
    </div>
    <div class="col-4 text-center bg-warning">
        <h1>FOOTER</h1>
    </div>
</div>

app/templates/components/sidebar.html
<div class="d-flex flex-column flex-shrink-0 p-3 bg-light sidebar">
    <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-color text-decoration-none">
      <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
      <span class="fs-4">Sidebar</span>
    </a>
    <hr>
    <ul class="nav nav-pills flex-column mb-auto">
      <li class="nav-item">
        <a href="#" class="nav-link active" aria-current="page">
          <i class="fa-solid fa-user"></i>
          MINHA CONTA
        </a>
      </li>
      <li>
        <a href="#" class="nav-link link-color">
            <i class="fa-solid fa-clipboard-list"></i>
          MEUS PEDIDOS
        </a>
      </li>
      <li>
        <a href="#" class="nav-link link-color">
            <i class="fa-solid fa-address-card"></i>
          MEUS DADOS
        </a>
      </li>
      <li>
        <a href="#" class="nav-link link-color">
            <i class="fa-solid fa-headset"></i>
          SUPORTE
        </a>
      </li>
      
    </ul>
    <hr>
    <div class="dropdown">
      <a href="#" class="d-flex align-items-center link-color text-decoration-none dropdown-toggle" id="dropdownUser2" data-bs-toggle="dropdown" aria-expanded="false">
        <img src="https://github.com/mdo.png" alt="" width="32" height="32" class="rounded-circle me-2">
        <strong>mdo</strong>
      </a>
      <ul class="dropdown-menu text-small shadow" aria-labelledby="dropdownUser2">
        <li><a class="dropdown-item" href="#">New project...</a></li>
        <li><a class="dropdown-item" href="#">Settings</a></li>
        <li><a class="dropdown-item" href="#">Profile</a></li>
        <li><hr class="dropdown-divider"></li>
        <li><a class="dropdown-item" href="#">Sign out</a></li>
      </ul>
    </div>
  </div>

app/templates/components/topbar.html
    <nav class="navbar navbar-expand-lg navbar-light fixed-top shadow" style="background-color: #001a5e;">
        <a class="navbar-brand mb-2" href="#">Flask Project</a>
        <button class="navbar-toggler mb-2" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent"> 
            <ul class="navbar-nav mx-auto me-auto mb-2 mb-lg-0 menu-principal">
                <li class="nav-item pe-4">
                <a class="nav-link active" aria-current="page" href="#">HOME</a>
                </li>
                <li class="nav-item pe-4">
                <a class="nav-link" href="#">QUEM SOMOS</a>
                </li>
                <li class="nav-item pe-4">
                    <a class="nav-link" href="#">PLANOS</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">CONTATO</a>
                </li>
            </ul>
            {% if current_user.is_authenticated %}
            <ul class="navbar-nav me-5 mb-lg-0 menu-user">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="fa-solid fa-user"></i> 
                        Olá {{ current_user.nome }}
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="{{ url_for('clientes.perfil') }}"><i class="fa-solid fa-id-badge fa-lg me-1"></i>Perfil</a></li>
                        <li><a class="dropdown-item" href="#"><i class="fa-solid fa-gear me-1"></i>Configurações</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="{{ url_for('clientes.logout') }}">Sair<i class="fa-solid fa-right-from-bracket ms-1"></i></a></li>
                    </ul>
                </li>
            </ul>
            {% else %}       
            <ul class="navbar-nav me-5 mb-lg-0 menu-login">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('clientes.login') }}"><i class="fa-solid fa-right-to-bracket me-1"></i>LOGIN</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('clientes.register') }}"><i class="fa-solid fa-circle-user me-1"></i>CRIAR CONTA</a>
                </li>
            </ul>
            {% endif %}
        </div> 
    </nav>